/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_pkmdz_chattool_rtmpnative_RTMPNative */

#ifndef _Included_com_pkmdz_chattool_rtmpnative_RTMPNative
#define _Included_com_pkmdz_chattool_rtmpnative_RTMPNative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_pkmdz_chattool_rtmpnative_RTMPNative
 * Method:    rtmpInit
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_pkmdz_chattool_rtmpnative_RTMPNative_rtmpInit
  (JNIEnv *, jobject);

/*
 * Class:     com_pkmdz_chattool_rtmpnative_RTMPNative
 * Method:    sendVMetaData
 * Signature: ([BI[BI)V
 */
JNIEXPORT void JNICALL Java_com_pkmdz_chattool_rtmpnative_RTMPNative_sendVMetaData
  (JNIEnv *, jobject, jbyteArray, jint, jbyteArray, jint);

/*
 * Class:     com_pkmdz_chattool_rtmpnative_RTMPNative
 * Method:    sendVideoData
 * Signature: ([BII)V
 */
JNIEXPORT void JNICALL Java_com_pkmdz_chattool_rtmpnative_RTMPNative_sendVideoData
  (JNIEnv *, jobject, jbyteArray, jint, jint);

/*
 * Class:     com_pkmdz_chattool_rtmpnative_RTMPNative
 * Method:    sendAMetaData
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_pkmdz_chattool_rtmpnative_RTMPNative_sendAMetaData
  (JNIEnv *, jobject);

/*
 * Class:     com_pkmdz_chattool_rtmpnative_RTMPNative
 * Method:    sendAudioData
 * Signature: ([BII)V
 */
JNIEXPORT void JNICALL Java_com_pkmdz_chattool_rtmpnative_RTMPNative_sendAudioData
  (JNIEnv *, jobject, jbyteArray, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
